### ISSUE TITLE
undefined method `delete' for false:FalseClass

### ISSUE THREAD

**Issue by tjwudi** [jwhitley/requirejs-rails#211]
When starting rails server (`rails s`), I got:

```
=> Booting Thin
=> Rails 4.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/Library/Ruby/Gems/2.0.0/gems/requirejs-rails-0.9.5/lib/requirejs/rails/config.rb:131:in `user_config=': undefined method `delete' for false:FalseClass (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/requirejs-rails-0.9.5/lib/requirejs/rails/engine.rb:100:in `process_user_config_file'
        from /Library/Ruby/Gems/2.0.0/gems/requirejs-rails-0.9.5/lib/requirejs/rails/engine.rb:19:in `block in <class:Engine>'
....
```

**Comment by tjwudi** [comment]
This is caused by providing an empty requirejs.yml. It will be better to raise an Exception here :)
