### ISSUE TITLE
Version 0.9.6 broken

### ISSUE THREAD

**Issue by dtognazzini** [jwhitley/requirejs-rails#221]
```
NameError: uninitialized constant ActionView::Helpers::AssetUrlHelper
/me/.rvm/gems/ruby-2.1.5/gems/requirejs-rails-0.9.6/lib/requirejs/rails/view_proxy.rb:5:in `<class:ViewProxy>'
/me/.rvm/gems/ruby-2.1.5/gems/requirejs-rails-0.9.6/lib/requirejs/rails/view_proxy.rb:3:in `<module:Rails>'
/me/.rvm/gems/ruby-2.1.5/gems/requirejs-rails-0.9.6/lib/requirejs/rails/view_proxy.rb:2:in `<module:Requirejs>'
/me/.rvm/gems/ruby-2.1.5/gems/requirejs-rails-0.9.6/lib/requirejs/rails/view_proxy.rb:1:in `<top (required)>'
/me/.rvm/gems/ruby-2.1.5/gems/requirejs-rails-0.9.6/app/helpers/requirejs_helper.rb:2:in `<top (required)>'
/me/.rvm/gems/ruby-2.1.5/gems/actionpack-3.2.20/lib/abstract_controller/helpers.rb:135:in `block in modules_for_helpers'
/me/.rvm/gems/ruby-2.1.5/gems/actionpack-3.2.20/lib/abstract_controller/helpers.rb:131:in `map!'
/me/.rvm/gems/ruby-2.1.5/gems/actionpack-3.2.20/lib/abstract_controller/helpers.rb:131:in `modules_for_helpers'
/me/.rvm/gems/ruby-2.1.5/gems/actionpack-3.2.20/lib/action_controller/metal/helpers.rb:92:in `modules_for_helpers'
/me/.rvm/gems/ruby-2.1.5/gems/actionpack-3.2.20/lib/abstract_controller/helpers.rb:95:in `helper'
/me/.rvm/gems/ruby-2.1.5/gems/actionpack-3.2.20/lib/action_controller/railties/paths.rb:18:in `block (2 levels) in with'
```

**Comment by dtognazzini** [comment]
Duplicate of #210

**Comment by chenxeed** [comment]
Hi i also get the problem when try to precompile in development.

run ```RAILS_ENV=development rake assets:precompile```

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/albert/.rvm/gems/ruby-2.2.1/gems/requirejs-rails-0.9.6/lib/tasks/requirejs-rails_tasks.rake:101:in `block (3 levels) in <top (required)>'
```

**Comment by carsomyr** [comment]
@dtognazzini Could you try the `master` branch? I already closed #210.

**Comment by carsomyr** [comment]
@chenxeed That's odd. Could you provide a sample Rails project so that I can reproduce?

**Comment by medyo** [comment]
Same bug as @chenxeed ! 
I reproduced the bug just by creating new project, adding requirejs gem then rake assets:precompile.
here is a demo app : https://gitlab.com/medyo/demo-requirejs

**Comment by dtognazzini** [comment]
How about using semver?

**Comment by carsomyr** [comment]
@dtognazzini I've been working on cleaning up the codebase. When this happens, just file semantic versioning as a separate issue.

**Comment by carsomyr** [comment]
@chenxeed @medyo @dtognazzini Could you guys point your `Gemfile`s to the `master` branch and try again?

**Comment by medyo** [comment]
Thanks @carsomyr the master branch works perfectly.

**Comment by md5** [comment]
I'll just add that I ran into the same issue and that using `master` (specifically commit f1016f05fbd7baabb5feb198a7abb1a37441deae) worked for me as well.
