### ISSUE TITLE
Error on run requirejs-rails, psych.rb:370:in `parse': (<unknown>): did not find expected key...

### ISSUE THREAD

**Issue by chenxeed** [jwhitley/requirejs-rails#239]
Hello, I just want to run my Rails app today with updated gem with requirejs-rails, and I found this error on failed start Rails.

psych.rb:370:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 184 column 5 (Psych::SyntaxError)

Now I cannot run my apps for a while. Wonder what's wrong.

**Comment by chenxeed** [comment]
Found the issue, my apologize.

It was on requirejs.yml, there's extra space that causes error.
