### ISSUE TITLE
Updating to 4.2.5.1 breaks app

### ISSUE THREAD

**Issue by jankeesvw** [jwhitley/requirejs-rails#258]
When I update my Rails version to 4.2.5.1 (the latest version) I run into this error, seems to be related to RequireJS-Rails:

Do you have any idea what to try?

```
Failure/Error: raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"

      ActionController::RoutingError:
        No route matches [GET] "/assets/underscore.js"
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:38:in `call_app'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `block in call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/static.rb:116:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:518:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capybara-2.5.0/lib/capybara/server.rb:19:in `call'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
      # /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
      #
      #   Showing full backtrace because every line was filtered out.
      #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
      #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

**Comment by jankeesvw** [comment]
I updated `rails` to `4.2.6` and `requirejs-rails` to `1.0.0` which solved the issue :point_up:.

But I then ran into the problem that the requirejs.yml changed, I updated it to this:

```yml
modules:
  - name: 'application'
paths:
  modernizr:
    - 'vendor/modernizr'
  jquery:
    - 'vendor/jquery'
  underscore:
    - 'vendor/underscore'
  require:
    - 'vendor/require'
  backbone:
    - 'vendor/backbone'
  moment:
    - 'vendor/moment'
  text:
    - 'vendor/text'
  jqueryui:
    - 'vendor/jquery_ujs'
  datepicker:
    - 'vendor/bootstrap-datepicker'
  nvd3:
    - 'vendor/nvd3'
  d3:
    - 'vendor/d3'
  stripe:
    - 'vendor/stripe'
  caretposition:
    - 'vendor/jquery.caretposition'
shim:
  nvd3:
    deps:
        - 'd3'
  jquery_ujs:
    deps:
      - 'jquery'
  caretposition:
    deps:
      - 'jquery'
  backbone:
    deps:
      - 'underscore'
      - 'jquery'
  datepicker:
    deps:
      - 'jquery'
